[package]
name = "empires"
version = "0.0.0"
edition = "2018"
authors = ["LJason <ljason@ljason.cn>"]
readme = "README.md"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"

[dependencies]
